services:
    alphanumeric-recognizer:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: alphanumeric-recognizer-img
        container_name: alphanumeric-recognizer
        ports:
            - "8080:8080"
        volumes:
            - ./server/models:/app/models
            - ./server/data:/app/data
    client-demo:
        build:
            context: ./client-demo
            dockerfile: Dockerfile
        image: client-demo-img
        container_name: client-demo
        ports:
            - 80:80